name: Quality

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  quality-go:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: test/go.mod
        check-latest: true
        cache: false
    - name: Install Make and GCC
      run: |
        export DEBIAN_NONINTERACTIVE=1
        sudo apt update
        sudo apt install -y make gcc
    - name: Build
      run: make build
    - name: Test
      run: make test